server:
  port: 18080
spring:
  profiles:
    active: dev
  application:
    name: mine_record
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true